#%RAML 1.0 Trait
queryParameters:
      updated_at_min: 
        required: false
        type: datetime
      created_at_max: 
        required: false
        type: datetime
      created_at_min: 
        required: false
        type: datetime
      updated_at_max: 
        required: false
        type: datetime
      ids:
        required: false
        type: string
      limit:
        required: false
        type: number