#%RAML 1.0 DataType

displayName: Error
type: object
properties:
  httpStatus:
    required: false
    displayName: httpStatus
    description: The HTTP status code
    type: integer
    format: int32
  message:
    required: false
    displayName: message
    description: Extended error information. Notice that error messages may change without warning and that programming logic should not rely upon the content of the message.
    type: string
  httpReason:
    required: false
    displayName: httpReason
    description: The name of the HTTP status code
    type: string
example:
  httpStatus: 404
  message: The specified resource was not found. Please check if resource id is correct.
  httpReason: Not Found