{
  "headers": {
    "date": "Sun, 05 May 2024 11:06:18 GMT",
    "content-type": "application/json; charset=utf-8",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "x-sorting-hat-podid": "335",
    "x-sorting-hat-shopid": "77580140844",
    "vary": "Accept-Encoding",
    "referrer-policy": "origin-when-cross-origin",
    "x-frame-options": "DENY",
    "x-shopid": "77580140844",
    "x-shardid": "335",
    "x-stats-userid": "",
    "x-stats-apiclientid": "111795830785",
    "x-stats-apipermissionid": "706412380496",
    "x-shopify-api-version": "2024-01",
    "link": "<https://nature-love-development.myshopify.com/admin/api/2024-01/checkouts.json?limit=10&page_info=eyJzdGF0dXMiOiJvcGVuIiwibGFzdF9pZCI6MTA1MTM3MDU1NjY1MDgsImxhc3RfdmFsdWUiOiIzNzMxNDUwNTM0MzI3NiIsImRpcmVjdGlvbiI6Im5leHQifQ>; rel=\"next\"",
    "strict-transport-security": "max-age=7889238",
    "x-request-id": "709bf97d-af2c-459b-88a2-4e621bbc12d8-1714907178",
    "server-timing": "processing;dur=276",
    "server-timing": "cfRequestDuration;dur=486.000061",
    "content-security-policy": "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fabandoned_checkouts&source%5Bsection%5D=admin_api&source%5Buuid%5D=709bf97d-af2c-459b-88a2-4e621bbc12d8-1714907178",
    "x-content-type-options": "nosniff",
    "x-download-options": "noopen",
    "x-permitted-cross-domain-policies": "none",
    "x-xss-protection": "1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fabandoned_checkouts&source%5Bsection%5D=admin_api&source%5Buuid%5D=709bf97d-af2c-459b-88a2-4e621bbc12d8-1714907178",
    "x-dc": "gcp-asia-south1,gcp-europe-west3,gcp-europe-west3",
    "cf-cache-status": "DYNAMIC",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=JhelaVaffQg2UCZetYnocVFfvGXxkomfzwRHRUl9NqEB2MtdnLKq%2B%2BKBJiiVyBDYk5Rowc2stGEO4vXitW9a4CAZhTapLsXU52lzHfPPO9tzBAaxZ1CZ0e2cPqQ73nqmMaiWuNc2%2FIK%2F1BetIjJqrS8wVRvqQs0z4H6H\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "87f042a819ec913f-MAA",
    "alt-svc": "h3=\":443\"; ma=86400"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}