{
  "headers": {
    "date": "Sun, 05 May 2024 11:00:39 GMT",
    "content-type": "application/json; charset=utf-8",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "x-sorting-hat-podid": "335",
    "x-sorting-hat-shopid": "77580140844",
    "vary": "Accept-Encoding",
    "referrer-policy": "origin-when-cross-origin",
    "x-frame-options": "DENY",
    "x-shopid": "77580140844",
    "x-shardid": "335",
    "x-stats-userid": "",
    "x-stats-apiclientid": "111795830785",
    "x-stats-apipermissionid": "706412380496",
    "x-shopify-api-version": "2024-01",
    "http_x_shopify_shop_api_call_limit": "1/400",
    "x-shopify-shop-api-call-limit": "1/400",
    "x-shopify-api-deprecated-reason": "https://shopify.dev/api/admin-rest/latest/resources/product",
    "link": "<https://nature-love-development.myshopify.com/admin/api/2024-01/products.json?limit=1&page_info=eyJsYXN0X2lkIjo4ODg4NzEzMjgxODM2LCJsYXN0X3ZhbHVlIjoiQWN0YXppbiBCaW8gS2l3aSBLYXBzZWxuIiwiZGlyZWN0aW9uIjoibmV4dCJ9>; rel=\"next\"",
    "strict-transport-security": "max-age=7889238",
    "x-request-id": "00f57e6e-4df8-44b6-9dbf-1f154f1ffec2-1714906839",
    "server-timing": "processing;dur=64",
    "server-timing": "cfRequestDuration;dur=495.999813",
    "content-security-policy": "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=00f57e6e-4df8-44b6-9dbf-1f154f1ffec2-1714906839",
    "x-content-type-options": "nosniff",
    "x-download-options": "noopen",
    "x-permitted-cross-domain-policies": "none",
    "x-xss-protection": "1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=00f57e6e-4df8-44b6-9dbf-1f154f1ffec2-1714906839",
    "x-dc": "gcp-asia-south1,gcp-europe-west3,gcp-europe-west3",
    "cf-cache-status": "DYNAMIC",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=zwafVZ%2BJhP3fsQQQIYo30Rii9sJBDJvNVl%2BmwzvjD2lXNjwPLBPoFlTzUMPA6Lfh1U9zPaEOJi8pHQp3YbnJIBhYE2KRFDIt5Z5Imp3qNlBvinDVafn1hEoK6%2Fa8hWthRziUQc6qu9rbM6Lu5%2BwE%2BAnXkibL10ChAnNg\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "87f03a601a849141-MAA",
    "alt-svc": "h3=\":443\"; ma=86400"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}