{
  "headers": {
    "date": "Sun, 05 May 2024 11:00:39 GMT",
    "content-type": "application/json; charset=utf-8",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "x-sorting-hat-podid": "336",
    "x-sorting-hat-shopid": "79462924625",
    "vary": "Accept-Encoding",
    "referrer-policy": "origin-when-cross-origin",
    "x-frame-options": "DENY",
    "x-shopid": "79462924625",
    "x-shardid": "336",
    "x-stats-userid": "",
    "x-stats-apiclientid": "111794814977",
    "x-stats-apipermissionid": "642001338705",
    "x-shopify-api-version": "2024-01",
    "http_x_shopify_shop_api_call_limit": "1/400",
    "x-shopify-shop-api-call-limit": "1/400",
    "x-shopify-api-deprecated-reason": "https://shopify.dev/api/admin-rest/latest/resources/product",
    "link": "<https://a12dd6.myshopify.com/admin/api/2024-01/products.json?limit=1&page_info=eyJsYXN0X2lkIjo5MDkwOTI0OTM3NTUzLCJsYXN0X3ZhbHVlIjoiQWZ0ZXIgV29ya291dCBCdW5kbGUiLCJkaXJlY3Rpb24iOiJuZXh0In0>; rel=\"next\"",
    "strict-transport-security": "max-age=7889238",
    "x-request-id": "7476fc60-e8af-46ed-9e4e-b2293fa9e3d2-1714906839",
    "server-timing": "processing;dur=89",
    "server-timing": "cfRequestDuration;dur=297.999859",
    "content-security-policy": "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=7476fc60-e8af-46ed-9e4e-b2293fa9e3d2-1714906839",
    "x-content-type-options": "nosniff",
    "x-download-options": "noopen",
    "x-permitted-cross-domain-policies": "none",
    "x-xss-protection": "1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Fproducts&source%5Bsection%5D=admin_api&source%5Buuid%5D=7476fc60-e8af-46ed-9e4e-b2293fa9e3d2-1714906839",
    "x-dc": "gcp-asia-south1,gcp-europe-west4,gcp-europe-west4",
    "cf-cache-status": "DYNAMIC",
    "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=%2FAYVD91mekOuy4eCEzzy%2B2Kcf0KKwczqGUUiy7IWqJi3WoXdAp2xJLLK%2FzW6bvqGvjQ%2FZehZmKhBgjeChrwX0X4zGpGhhLcqPBGj8ywzziccoPx8sAap8O7DfALqfTZuBC%2BD6l4HQdCo6Q%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
    "nel": "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
    "server": "cloudflare",
    "cf-ray": "87f03a6019599146-MAA",
    "alt-svc": "h3=\":443\"; ma=86400"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}