{
  "checkouts": [
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLXVzLWNlbnRyYWwxOjAxSEtNUktTWjhEUzM3QjJBVFRQMFhOWlM1",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-06T16:09:36+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "fh@florian-herzog.net",
      "gateway": null,
      "id": 37253987107116,
      "landing_site": "/",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "cdd08a92f3179e81ac9ddda3d3eb9a26",
      "total_weight": 91,
      "updated_at": "2024-02-06T16:09:36+01:00",
      "user_id": null,
      "customer": {
        "id": 7152579772716,
        "email": "fh@florian-herzog.net",
        "created_at": "2023-07-31T23:34:52+02:00",
        "updated_at": "2024-02-06T16:09:36+01:00",
        "first_name": "Florian",
        "last_name": "Herzog",
        "orders_count": 3,
        "state": "disabled",
        "total_spent": "264.25",
        "last_order_id": 5609288827180,
        "note": "",
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009403867",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7152579772716",
        "default_address": {
          "id": 9360292249900,
          "customer_id": 7152579772716,
          "first_name": "Florian",
          "last_name": "Herzog",
          "company": null,
          "address1": "Auf den Kreuzwiesen 1A",
          "address2": null,
          "city": "Immenstadt im Allgäu",
          "province": null,
          "country": "Germany",
          "zip": "87509",
          "phone": null,
          "name": "Florian Herzog",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37253987107116",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "18.99",
      "total_price": "18.99",
      "total_tax": "1.24",
      "subtotal_price": "18.99",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLXVzLWNlbnRyYWwxOjAxSEtNUktTWjhEUzM3QjJBVFRQMFhOWlM1/recover?key=18195d64613a708b12734523e98907e5&locale=de-DE",
      "shipping_lines": [],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.24",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.24",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": null,
      "billing_address": null,
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 91,
          "origin_location_id": null,
          "presentment_title": "Zink Tabletten",
          "presentment_variant_title": "365 Tabletten_für 1 Jahr",
          "product_id": 8388746248492,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_zt_365_25mg",
          "taxable": true,
          "title": "Zink Tabletten",
          "variant_id": 45898091790636,
          "variant_title": "365 Tabletten_für 1 Jahr",
          "variant_price": "18.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 91,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "18.99",
          "price": "18.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.24",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.24",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLXVzLWNlbnRyYWwxOjAxSEs1OTZYQ1JKR1laM0JKQ1dLMEEwTTdK",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-06T10:21:04+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "nicole.peikert@natsana.com",
      "gateway": null,
      "id": 37257518186796,
      "landing_site": "/",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "7465b0986097b760ec1e1117a646d300",
      "total_weight": 104,
      "updated_at": "2024-02-13T17:39:08+01:00",
      "user_id": null,
      "customer": {
        "id": 6997569667372,
        "email": "nicole.peikert@natsana.com",
        "created_at": "2023-06-13T12:32:10+02:00",
        "updated_at": "2024-04-29T09:56:04+02:00",
        "first_name": "Nicole",
        "last_name": "Peikert",
        "orders_count": 18,
        "state": "enabled",
        "total_spent": "33.49",
        "last_order_id": 6087901479248,
        "note": "",
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009471531",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "subscribed",
          "opt_in_level": "unknown",
          "consent_updated_at": "2022-06-03T15:56:49+02:00"
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/6997569667372",
        "default_address": {
          "id": 10367884591440,
          "customer_id": 6997569667372,
          "first_name": "Nicole",
          "last_name": "Peikert",
          "company": null,
          "address1": "Immermannstraße 45",
          "address2": "Tauron Ventures GmbH",
          "city": "Düsseldorf",
          "province": null,
          "country": "Germany",
          "zip": "40210",
          "phone": null,
          "name": "Nicole Peikert",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37257518186796",
      "discount_codes": [
        {
          "code": "GÜTENACHT",
          "amount": "15.99",
          "type": "percentage"
        }
      ],
      "total_discounts": "15.99",
      "total_line_items_price": "36.98",
      "total_price": "24.49",
      "total_tax": "1.60",
      "subtotal_price": "20.99",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLXVzLWNlbnRyYWwxOjAxSEs1OTZYQ1JKR1laM0JKQ1dLMEEwTTdK/recover?key=c2d73587fba0dc19a63ac9afa0c5503a&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "ddcdfe4a2b55b6f881e43f740ecb8dcb",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.60",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.60",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Nicole",
        "address1": "Barmer Str. 13",
        "phone": null,
        "city": "Dortmund",
        "zip": "44137",
        "province": null,
        "country": "DE",
        "last_name": "Peikert",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Nicole Peikert",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Nicole",
        "address1": "Barmer Str. 13",
        "phone": null,
        "city": "Dortmund",
        "zip": "44137",
        "province": null,
        "country": "DE",
        "last_name": "Peikert",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Nicole Peikert",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 30,
          "origin_location_id": null,
          "presentment_title": "Melatoninspray",
          "presentment_variant_title": "Blutorange / 30 ml_für 105 Nächte",
          "product_id": 8388747690284,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_melatonin_spray_blutorange",
          "taxable": true,
          "title": "Melatoninspray",
          "variant_id": 45400182751532,
          "variant_title": "Blutorange / 30 ml_für 105 Nächte",
          "variant_price": "15.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "volume",
            "quantity_value": 30,
            "quantity_unit": "ml",
            "reference_value": 1,
            "reference_unit": "l"
          },
          "rank": null,
          "line_price": "15.99",
          "price": "15.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "0.00",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.00",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 74,
          "origin_location_id": null,
          "presentment_title": "Nacht Kapseln",
          "presentment_variant_title": "90 Kapseln_für 3 Monate",
          "product_id": 8670615241004,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_nacht_90",
          "taxable": true,
          "title": "Nacht Kapseln",
          "variant_id": 46845875061036,
          "variant_title": "90 Kapseln_für 3 Monate",
          "variant_price": "20.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 74,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "20.99",
          "price": "20.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.37",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.37",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhORjZYNUdTM1pORk5BTTc0M0M4TkZWNg",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-07T16:08:34+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "sarahkoehler82@gmail.com",
      "gateway": null,
      "id": 37302183854380,
      "landing_site": "/?utm_source=google_paid&utm_medium=paid_sea&utm_campaign=G_NL_DE_Brand_brand&utm_content=G_NL_DE_Brand_brand_db&gad_source=1&gclid=CjwKCAiA8YyuBhBSEiwA5R3-E6W7dfb5thv7SIRZbjsT_tVkPhcaUt91-xNoq9fR7mvRG5mrRWnKFRoCUOcQAvD_BwE",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "2f80ab3aeccb0767b9ebede118e836db",
      "total_weight": 2240,
      "updated_at": "2024-02-07T16:08:34+01:00",
      "user_id": null,
      "customer": {
        "id": 7782940737836,
        "email": "sarahkoehler82@gmail.com",
        "created_at": "2024-02-07T16:08:34+01:00",
        "updated_at": "2024-02-26T14:16:04+01:00",
        "first_name": "Sarah",
        "last_name": "Köhler",
        "orders_count": 0,
        "state": "disabled",
        "total_spent": "0.00",
        "last_order_id": null,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": null,
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7782940737836",
        "default_address": {
          "id": 9883956347180,
          "customer_id": 7782940737836,
          "first_name": "Sarah",
          "last_name": "Köhler",
          "company": null,
          "address1": "Pfarrgasse 4",
          "address2": null,
          "city": "Nordheim am Main",
          "province": null,
          "country": "Germany",
          "zip": "97334",
          "phone": null,
          "name": "Sarah Köhler",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37302183854380",
      "discount_codes": [
        {
          "code": "ILOVENATURELOVE",
          "amount": "13.90",
          "type": "percentage"
        }
      ],
      "total_discounts": "13.90",
      "total_line_items_price": "138.94",
      "total_price": "125.04",
      "total_tax": "8.19",
      "subtotal_price": "125.04",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhORjZYNUdTM1pORk5BTTc0M0M4TkZWNg/recover?key=5851876b56dbcac96fc5879b8e7a5fc0&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Versandkostenfrei in Deutschland ab 50€",
          "price": "0.00",
          "source": "shopify",
          "title": "Versandkostenfrei in Deutschland ab 50€",
          "presentment_title": "Versandkostenfrei in Deutschland ab 50€",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "78a1c0bc106280a70e86d09d2a240e0a",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.00",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.00",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "8.19",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "8.19",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Sarah",
        "address1": "Pfarrgasse 4",
        "phone": null,
        "city": "Nordheim am Main",
        "zip": "97334",
        "province": null,
        "country": "DE",
        "last_name": "Köhler",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Sarah Köhler",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Sarah",
        "address1": "Pfarrgasse 4",
        "phone": null,
        "city": "Nordheim am Main",
        "zip": "97334",
        "province": null,
        "country": "DE",
        "last_name": "Köhler",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Sarah Köhler",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 55,
          "origin_location_id": null,
          "presentment_title": "Omega 3 aus Algenöl Kapseln",
          "presentment_variant_title": "90 Kapseln_für 1 Monat",
          "product_id": 8388745298220,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_omega3_algenoel",
          "taxable": true,
          "title": "Omega 3 aus Algenöl Kapseln",
          "variant_id": 45886172889388,
          "variant_title": "90 Kapseln_für 1 Monat",
          "variant_price": "26.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 55,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "26.99",
          "price": "26.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.59",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.59",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 84,
          "origin_location_id": null,
          "presentment_title": "Vitamin B Komplex Kapseln",
          "presentment_variant_title": "180 Kapseln_für 6 Monate",
          "product_id": 8388745560364,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_vbk_180",
          "taxable": true,
          "title": "Vitamin B Komplex Kapseln",
          "variant_id": 45897071657260,
          "variant_title": "180 Kapseln_für 6 Monate",
          "variant_price": "29.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 84,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "29.99",
          "price": "29.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.77",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.77",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 1417,
          "origin_location_id": null,
          "presentment_title": "Vitamin D3 5000 I.E. Tropfen",
          "presentment_variant_title": "50 ml_1.700 Tropfen",
          "product_id": 8388744511788,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_vd3_25mcg",
          "taxable": true,
          "title": "Vitamin D3 5000 I.E. Tropfen",
          "variant_id": 45897610559788,
          "variant_title": "50 ml_1.700 Tropfen",
          "variant_price": "16.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "volume",
            "quantity_value": 50,
            "quantity_unit": "ml",
            "reference_value": 1,
            "reference_unit": "l"
          },
          "rank": null,
          "line_price": "16.99",
          "price": "16.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.00",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.00",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 180,
          "origin_location_id": null,
          "presentment_title": "Eisen & Vitamin C Tabletten",
          "presentment_variant_title": "240 Tabletten_für 8 Monate",
          "product_id": 8388747919660,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_et_120_40mg_40mg",
          "taxable": true,
          "title": "Eisen & Vitamin C Tabletten",
          "variant_id": 45725613916460,
          "variant_title": "240 Tabletten_für 8 Monate",
          "variant_price": "16.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 180,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "16.99",
          "price": "16.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.00",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.00",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 204,
          "origin_location_id": null,
          "presentment_title": "Bio Curcuma Kapseln",
          "presentment_variant_title": "240 Kapseln_für 1 Monat",
          "product_id": 8388748411180,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_bckk_3000mg_180",
          "taxable": true,
          "title": "Bio Curcuma Kapseln",
          "variant_id": 45725358227756,
          "variant_title": "240 Kapseln_für 1 Monat",
          "variant_price": "27.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 204,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "27.99",
          "price": "27.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.65",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.65",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 300,
          "origin_location_id": null,
          "presentment_title": "Green Superfood Pulver",
          "presentment_variant_title": "300g Pulver_für 1 Monat",
          "product_id": 8875259593004,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "NL_GreenSuperfood_Pulver_300",
          "taxable": true,
          "title": "Green Superfood Pulver",
          "variant_id": 47418492256556,
          "variant_title": "300g Pulver_für 1 Monat",
          "variant_price": "19.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 300,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "19.99",
          "price": "19.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.18",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.18",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWFzaWEtc291dGhlYXN0MTowMUhNVjMwV00zVjQ1TkU3WEo1OEtYMjBEUA",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-13T07:37:37+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "gaurav@bytecodetechnologies.in",
      "gateway": null,
      "id": 37304349655340,
      "landing_site": "/?_ab=0&_fd=0&_sc=1",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "8533d6896ba734a436c73f818d80ce17",
      "total_weight": 500,
      "updated_at": "2024-02-28T11:15:02+01:00",
      "user_id": null,
      "customer": {
        "id": 7801938706732,
        "email": "gaurav@bytecodetechnologies.in",
        "created_at": "2024-02-13T07:23:56+01:00",
        "updated_at": "2024-02-28T11:15:02+01:00",
        "first_name": null,
        "last_name": null,
        "orders_count": 0,
        "state": "disabled",
        "total_spent": "0.00",
        "last_order_id": null,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": null,
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7801938706732"
      },
      "source": null,
      "source_name": "web",
      "name": "#37304349655340",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "296.84",
      "total_price": "296.84",
      "total_tax": "19.42",
      "subtotal_price": "296.84",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWFzaWEtc291dGhlYXN0MTowMUhNVjMwV00zVjQ1TkU3WEo1OEtYMjBEUA/recover?key=220143d0e94c6ab1f91ea900448259e4&locale=de-DE",
      "shipping_lines": [],
      "tax_lines": [
        {
          "position": 1,
          "price": "19.42",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "19.42",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": null,
      "billing_address": null,
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 30,
          "origin_location_id": null,
          "presentment_title": "Vitamin D3 & K2 Tropfen",
          "presentment_variant_title": "30 ml_1.020 Tropfen",
          "product_id": 8388744773932,
          "properties": [],
          "quantity": 15,
          "requires_shipping": true,
          "sku": "nl_vd3_k2_30ml",
          "taxable": true,
          "title": "Vitamin D3 & K2 Tropfen",
          "variant_id": 47931208335660,
          "variant_title": "30 ml_1.020 Tropfen",
          "variant_price": "17.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "volume",
            "quantity_value": 30,
            "quantity_unit": "ml",
            "reference_value": 1,
            "reference_unit": "l"
          },
          "rank": null,
          "line_price": "269.85",
          "price": "17.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "17.65",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "17.65",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 50,
          "origin_location_id": null,
          "presentment_title": "Vitamin D3 & K2 Tropfen",
          "presentment_variant_title": "50 ml_1.700 Tropfen",
          "product_id": 8388744773932,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_vd3_k2_50ml",
          "taxable": true,
          "title": "Vitamin D3 & K2 Tropfen",
          "variant_id": 45897693790508,
          "variant_title": "50 ml_1.700 Tropfen",
          "variant_price": "26.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "volume",
            "quantity_value": 50,
            "quantity_unit": "ml",
            "reference_value": 1,
            "reference_unit": "l"
          },
          "rank": null,
          "line_price": "26.99",
          "price": "26.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.77",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.77",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLXVzLWNlbnRyYWwxOjAxSE5WNzFYRllLRkJQMlJLQURKRVBRWVFC",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:17:34+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "anjakirchhof@gmx.de",
      "gateway": null,
      "id": 37314467397932,
      "landing_site": "/?utm_source=google_paid&utm_medium=paid_sea&utm_campaign=G_NL_DE_Brand_brand&utm_content=G_NL_DE_Brand_brand_db&gad_source=1&gclid=CjwKCAiAiP2tBhBXEiwACslfnu1JbbuQPhV6FRUZVvNzi0ntisjRPLZZ7gaMrhnkdPOpzlz_XdOO0BoCPJwQAvD_BwE",
      "location_id": null,
      "note": null,
      "note_attributes": [
        {
          "name": "from",
          "value": "new-customer-accounts"
        }
      ],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "089df7ebbbd34d3429b1ee5e75a9e4d4",
      "total_weight": 244,
      "updated_at": "2024-02-05T12:17:34+01:00",
      "user_id": null,
      "customer": {
        "id": 7178713071916,
        "email": "anjakirchhof@gmx.de",
        "created_at": "2023-08-09T12:23:40+02:00",
        "updated_at": "2024-03-19T21:47:07+01:00",
        "first_name": "Anja",
        "last_name": "Wildgrube",
        "orders_count": 6,
        "state": "enabled",
        "total_spent": "357.70",
        "last_order_id": 5788447539500,
        "note": "",
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009456078",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7178713071916",
        "default_address": {
          "id": 9706136338732,
          "customer_id": 7178713071916,
          "first_name": "Anja",
          "last_name": "Wildgrube",
          "company": "",
          "address1": "Karl-Marx-Straße 5a",
          "address2": "OT Wolfen",
          "city": "Bitterfeld-Wolfen",
          "province": "",
          "country": "Germany",
          "zip": "06766",
          "phone": "",
          "name": "Anja Wildgrube",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37314467397932",
      "discount_codes": [
        {
          "code": "MA-5232FN83-CB",
          "amount": "6.60",
          "type": "percentage"
        }
      ],
      "total_discounts": "6.60",
      "total_line_items_price": "54.98",
      "total_price": "51.88",
      "total_tax": "3.39",
      "subtotal_price": "48.38",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLXVzLWNlbnRyYWwxOjAxSE5WNzFYRllLRkJQMlJLQURKRVBRWVFC/recover?key=2c4bd18c57432275de72f8d1083e9ef1&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "744af3b6c4976ee58bdc3f576a49a56a",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "3.39",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "3.39",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Anja",
        "address1": "Karl-Marx-Straße 5a",
        "phone": null,
        "city": "Bitterfeld-Wolfen",
        "zip": "06766",
        "province": null,
        "country": "DE",
        "last_name": "Wildgrube",
        "address2": "OT Wolfen",
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Anja Wildgrube",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Anja",
        "address1": "Karl-Marx-Straße 5a",
        "phone": null,
        "city": "Bitterfeld-Wolfen",
        "zip": "06766",
        "province": null,
        "country": "DE",
        "last_name": "Wildgrube",
        "address2": "OT Wolfen",
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Anja Wildgrube",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 175,
          "origin_location_id": null,
          "presentment_title": "Bio Ashwagandha Kapseln",
          "presentment_variant_title": "240 Kapseln_für 80 Tage",
          "product_id": 8388745855276,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_bashw_240",
          "taxable": true,
          "title": "Bio Ashwagandha Kapseln",
          "variant_id": 45725308289324,
          "variant_title": "240 Kapseln_für 80 Tage",
          "variant_price": "26.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 175,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "26.99",
          "price": "26.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.55",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.55",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 69,
          "origin_location_id": null,
          "presentment_title": "Curcuma Extrakt Kapseln",
          "presentment_variant_title": "90 Kapseln_für 9 Monate",
          "product_id": 8388747034924,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_ckk_90",
          "taxable": true,
          "title": "Curcuma Extrakt Kapseln",
          "variant_id": 45725511680300,
          "variant_title": "90 Kapseln_für 9 Monate",
          "variant_price": "27.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 69,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "27.99",
          "price": "27.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.61",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.61",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0ZRUkhLMUVaSDNSN0NDVDU1NVIzQw",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:31:10+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "keramikschuppen@web.de",
      "gateway": null,
      "id": 37314485125420,
      "landing_site": "/products/opc-traubenkernextrakt-kapseln-180-stuck-im-3-monatsvorrat-440mg-opc-je-tagesdosis?utm_source=google_paid&utm_medium=paid_sea&utm_campaign=G_NL_DE_PDP_4_Pflanzenstoffe_OPC-Traubenkernextrakt-Kapseln&utm_content=G_NL_DE_PDP_4_Pflanzenstoffe_OPC-Traubenkernextrakt-Kapseln_promo_neujahr_2024&gad_source=1&gclid=CjwKCAiA5L2tBhBTEiwAdSxJX31FqJzgQLxM3shWRlGAqUvEWh8ZVaH3F7BRiEbQsoCboe3gIqRSKxoCt-YQAvD_BwE",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "2cdbb10b26594a2e78996850a8025a6f",
      "total_weight": 467,
      "updated_at": "2024-02-05T12:31:10+01:00",
      "user_id": null,
      "customer": {
        "id": 7776335659308,
        "email": "keramikschuppen@web.de",
        "created_at": "2024-02-05T12:31:10+01:00",
        "updated_at": "2024-03-04T21:36:09+01:00",
        "first_name": "Britta",
        "last_name": "Wokersin",
        "orders_count": 1,
        "state": "disabled",
        "total_spent": "50.98",
        "last_order_id": 5772155650348,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009449920",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7776335659308",
        "default_address": {
          "id": 9877126414636,
          "customer_id": 7776335659308,
          "first_name": "Britta",
          "last_name": "Wokersin",
          "company": null,
          "address1": "Dorfstraße 10",
          "address2": null,
          "city": "Karnin",
          "province": null,
          "country": "Germany",
          "zip": "18469",
          "phone": null,
          "name": "Britta Wokersin",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37314485125420",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "50.98",
      "total_price": "50.98",
      "total_tax": "3.33",
      "subtotal_price": "50.98",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0ZRUkhLMUVaSDNSN0NDVDU1NVIzQw/recover?key=0b0ba3a1769856b0ac9589926597a894&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Versandkostenfrei in Deutschland ab 50€",
          "price": "0.00",
          "source": "shopify",
          "title": "Versandkostenfrei in Deutschland ab 50€",
          "presentment_title": "Versandkostenfrei in Deutschland ab 50€",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "c67ff6624bed74a8e13a3c9e9184f773",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.00",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.00",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "3.33",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "3.33",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Britta",
        "address1": "Dorfstraße 10",
        "phone": null,
        "city": "Karnin",
        "zip": "18469",
        "province": null,
        "country": "DE",
        "last_name": "Wokersin",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Britta Wokersin",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Britta",
        "address1": "Dorfstraße 10",
        "phone": null,
        "city": "Karnin",
        "zip": "18469",
        "province": null,
        "country": "DE",
        "last_name": "Wokersin",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Britta Wokersin",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 90,
          "origin_location_id": null,
          "presentment_title": "OPC Traubenkernextrakt Kapseln",
          "presentment_variant_title": "180 Kapseln_für 3 Monate",
          "product_id": 8388747165996,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_opc_180_440mg",
          "taxable": true,
          "title": "OPC Traubenkernextrakt Kapseln",
          "variant_id": 45886184292652,
          "variant_title": "180 Kapseln_für 3 Monate",
          "variant_price": "24.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 90,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "24.99",
          "price": "24.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.63",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.63",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        },
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 377,
          "origin_location_id": null,
          "presentment_title": "MSM Tabletten",
          "presentment_variant_title": "365 Tabletten_für 6 Monate",
          "product_id": 8388745756972,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_msm_365_2000mg",
          "taxable": true,
          "title": "MSM Tabletten",
          "variant_id": 45886050566444,
          "variant_title": "365 Tabletten_für 6 Monate",
          "variant_price": "25.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 377,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "25.99",
          "price": "25.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.70",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.70",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0ZYTUs5TUZKUTdUVDI4OUVXOTJEQQ",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:33:00+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "traute.ehlerding@gmail.com",
      "gateway": null,
      "id": 37314487189804,
      "landing_site": "/collections/all/products/opc-traubenkernextrakt-kapseln-180-stuck-im-3-monatsvorrat-440mg-opc-je-tagesdosis?utm_source=google_paid&utm_medium=paid_shopping&utm_campaign=G_NL_DE_PLA_4_Pflanzenstoffe_nonbrand&utm_content=G_NL_DE_PLA_4_Pflanzenstoffe_nonbrand_product_opc_traubenkernextrakt_kapseln&gad=1&gclid=Cj0KCQjwmvSoBhDOARIsAK6aV7jfUYTTHIWnC4Es2z1E4VJymzPN6gS4sqzuH-fK8koeekdrYfCxxfgaAjE9EALw_wcB",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "1a4494e2f69b033fda5b367e5641b824",
      "total_weight": 90,
      "updated_at": "2024-02-05T12:33:00+01:00",
      "user_id": null,
      "customer": {
        "id": 7445742846252,
        "email": "traute.ehlerding@gmail.com",
        "created_at": "2023-10-20T10:01:21+02:00",
        "updated_at": "2024-03-12T09:18:42+01:00",
        "first_name": "Traute",
        "last_name": "Ehlerding",
        "orders_count": 2,
        "state": "disabled",
        "total_spent": "48.44",
        "last_order_id": 5780585972012,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009452622",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7445742846252",
        "default_address": {
          "id": 10014802706732,
          "customer_id": 7445742846252,
          "first_name": "Traute",
          "last_name": "Ehlerding",
          "company": null,
          "address1": "Haslangstraße 21",
          "address2": null,
          "city": "Ingolstadt",
          "province": null,
          "country": "Germany",
          "zip": "85049",
          "phone": null,
          "name": "Traute Ehlerding",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37314487189804",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "24.99",
      "total_price": "28.49",
      "total_tax": "1.86",
      "subtotal_price": "24.99",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0ZYTUs5TUZKUTdUVDI4OUVXOTJEQQ/recover?key=3cf71c23058039a861c4f11655c79aa2&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "136f9d3db2bcb3d07f4354b94f97e26f",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.86",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.86",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Traute",
        "address1": "Haslangstr",
        "phone": null,
        "city": "Ingolstadt",
        "zip": "85049",
        "province": null,
        "country": "DE",
        "last_name": "Ehlerding",
        "address2": "21",
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Traute Ehlerding",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Traute",
        "address1": "Haslangstr",
        "phone": null,
        "city": "Ingolstadt",
        "zip": "85049",
        "province": null,
        "country": "DE",
        "last_name": "Ehlerding",
        "address2": "21",
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Traute Ehlerding",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 90,
          "origin_location_id": null,
          "presentment_title": "OPC Traubenkernextrakt Kapseln",
          "presentment_variant_title": "180 Kapseln_für 3 Monate",
          "product_id": 8388747165996,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_opc_180_440mg",
          "taxable": true,
          "title": "OPC Traubenkernextrakt Kapseln",
          "variant_id": 45886184292652,
          "variant_title": "180 Kapseln_für 3 Monate",
          "variant_price": "24.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 90,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "24.99",
          "price": "24.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.63",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.63",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0c5M0NHVDYwNUZNRzRZQUIxMEhSNA",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:38:00+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "hanuta33@gmx.de",
      "gateway": null,
      "id": 37314495873324,
      "landing_site": "/products/zink-tabletten-365-stuck-im-jahresvorrat-25mg-zink-pro-tablette?utm_source=google_paid&utm_medium=paid_shopping&utm_campaign=G_NL_DE_PLA_4_PMAX_nonbrand_Schönheit_und_Anti-Aging&utm_content=G_NL_DE_PLA_4_PMAX_nonbrand_Schönheit_und_Anti-Aging_product&gad_source=1&gclid=EAIaIQobChMIjvaJnouUhAMV_pRQBh0fywAcEAQYAyABEgLsrvD_BwE",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "0a4ac6f012511ba5f2337bed478388a4",
      "total_weight": 91,
      "updated_at": "2024-02-05T12:38:00+01:00",
      "user_id": null,
      "customer": {
        "id": 7776332218668,
        "email": "hanuta33@gmx.de",
        "created_at": "2024-02-05T12:28:52+01:00",
        "updated_at": "2024-02-05T12:38:00+01:00",
        "first_name": "Anna",
        "last_name": "Simon",
        "orders_count": 0,
        "state": "disabled",
        "total_spent": "0.00",
        "last_order_id": null,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": null,
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7776332218668"
      },
      "source": null,
      "source_name": "web",
      "name": "#37314495873324",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "18.99",
      "total_price": "22.49",
      "total_tax": "1.47",
      "subtotal_price": "18.99",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0c5M0NHVDYwNUZNRzRZQUIxMEhSNA/recover?key=2c677aa4beb58f567c9b5d128d85b86e&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "c825dfabbd726416f097215a7c13d409",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.47",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.47",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Anna",
        "address1": "Böcklinstr. 21A",
        "phone": null,
        "city": "Altrip",
        "zip": "67122",
        "province": null,
        "country": "DE",
        "last_name": "Simon",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Anna Simon",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Anna",
        "address1": "Böcklinstr. 21A",
        "phone": null,
        "city": "Altrip",
        "zip": "67122",
        "province": null,
        "country": "DE",
        "last_name": "Simon",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Anna Simon",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 91,
          "origin_location_id": null,
          "presentment_title": "Zink Tabletten",
          "presentment_variant_title": "365 Tabletten_für 1 Jahr",
          "product_id": 8388746248492,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_zt_365_25mg",
          "taxable": true,
          "title": "Zink Tabletten",
          "variant_id": 45898091790636,
          "variant_title": "365 Tabletten_für 1 Jahr",
          "variant_price": "18.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 91,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "18.99",
          "price": "18.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.24",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.24",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0c2UlhKUjFKWFQ2TUE3UVpUUDZTMg",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:44:30+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "silja.weindl@gmail.com",
      "gateway": null,
      "id": 37314504327468,
      "landing_site": "/products/biotin-komplex-365-tabletten-im-jahresvorrat?utm_source=google_paid&utm_medium=paid_shopping&utm_campaign=G_NL_DE_PLA_4_PMAX_nonbrand_Schönheit_und_Anti-Aging&utm_content=G_NL_DE_PLA_4_PMAX_nonbrand_Schönheit_und_Anti-Aging_product&gad_source=1&gclid=EAIaIQobChMIs9qahouUhAMVEqWDBx3SvwDhEAQYAyABEgJAzfD_BwE",
      "location_id": null,
      "note": null,
      "note_attributes": [],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "77a79abbca40eeae0b6481a40f5f0802",
      "total_weight": 146,
      "updated_at": "2024-02-05T12:44:30+01:00",
      "user_id": null,
      "customer": {
        "id": 7776352665900,
        "email": "silja.weindl@gmail.com",
        "created_at": "2024-02-05T12:44:31+01:00",
        "updated_at": "2024-02-05T12:44:31+01:00",
        "first_name": "Silja",
        "last_name": "Weindl",
        "orders_count": 0,
        "state": "disabled",
        "total_spent": "0.00",
        "last_order_id": null,
        "note": null,
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": null,
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7776352665900",
        "default_address": {
          "id": 9877144043820,
          "customer_id": 7776352665900,
          "first_name": "Silja",
          "last_name": "Weindl",
          "company": null,
          "address1": "Kuckucksblumenstrasse, 18a",
          "address2": null,
          "city": "München",
          "province": null,
          "country": "Germany",
          "zip": "80995",
          "phone": null,
          "name": "Silja Weindl",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37314504327468",
      "discount_codes": [],
      "total_discounts": "0.00",
      "total_line_items_price": "24.99",
      "total_price": "28.49",
      "total_tax": "1.86",
      "subtotal_price": "24.99",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0c2UlhKUjFKWFQ2TUE3UVpUUDZTMg/recover?key=9d3ddef86f5b8d56155026021f1f8346&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "2b85fbf8b25aaafec3e8ecd63ef33fe3",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.86",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.86",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Silja",
        "address1": "Kuckucksblumenstrasse, 18a",
        "phone": null,
        "city": "München",
        "zip": "80995",
        "province": null,
        "country": "DE",
        "last_name": "Weindl",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Silja Weindl",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Silja",
        "address1": "Kuckucksblumenstrasse, 18a",
        "phone": null,
        "city": "München",
        "zip": "80995",
        "province": null,
        "country": "DE",
        "last_name": "Weindl",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Silja Weindl",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 146,
          "origin_location_id": null,
          "presentment_title": "Biotin Komplex Tabletten",
          "presentment_variant_title": "365 Tabletten_für 1 Jahr",
          "product_id": 8388746477868,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_biotin_komplex",
          "taxable": true,
          "title": "Biotin Komplex Tabletten",
          "variant_id": 45725452861740,
          "variant_title": "365 Tabletten_für 1 Jahr",
          "variant_price": "24.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 146,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "24.99",
          "price": "24.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.63",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.63",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    },
    {
      "buyer_accepts_marketing": false,
      "cart_token": "Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0dTSERFQzROWkQ3WkM1TU1GNFZQSw",
      "closed_at": null,
      "completed_at": null,
      "created_at": "2024-02-05T12:50:04+01:00",
      "currency": "EUR",
      "presentment_currency": "EUR",
      "customer_locale": "de-DE",
      "device_id": null,
      "email": "tdreyse@gmx.de",
      "gateway": null,
      "id": 37314505343276,
      "landing_site": "/",
      "location_id": null,
      "note": null,
      "note_attributes": [
        {
          "name": "from",
          "value": "new-customer-accounts"
        }
      ],
      "phone": null,
      "referring_site": "https://www.google.com/",
      "source_identifier": null,
      "source_url": null,
      "taxes_included": true,
      "token": "19d79517d3937e2136075076e1db9c1d",
      "total_weight": 217,
      "updated_at": "2024-02-05T12:50:04+01:00",
      "user_id": null,
      "customer": {
        "id": 7154262802732,
        "email": "tdreyse@gmx.de",
        "created_at": "2023-08-01T01:59:04+02:00",
        "updated_at": "2024-02-05T12:50:04+01:00",
        "first_name": "Thomas",
        "last_name": "Dreyse",
        "orders_count": 3,
        "state": "disabled",
        "total_spent": "94.17",
        "last_order_id": 5612288311596,
        "note": "",
        "verified_email": true,
        "multipass_identifier": null,
        "tax_exempt": false,
        "tags": "",
        "last_order_name": "#1009404888",
        "currency": "EUR",
        "phone": null,
        "tax_exemptions": [],
        "email_marketing_consent": {
          "state": "not_subscribed",
          "opt_in_level": "confirmed_opt_in",
          "consent_updated_at": null
        },
        "sms_marketing_consent": null,
        "admin_graphql_api_id": "gid://shopify/Customer/7154262802732",
        "default_address": {
          "id": 9362269733164,
          "customer_id": 7154262802732,
          "first_name": "Thomas",
          "last_name": "Dreyse",
          "company": null,
          "address1": "Stromberger Str. 2a",
          "address2": null,
          "city": "Daxweiler",
          "province": null,
          "country": "Germany",
          "zip": "55442",
          "phone": "+4967247449",
          "name": "Thomas Dreyse",
          "province_code": null,
          "country_code": "DE",
          "country_name": "Germany",
          "default": true
        }
      },
      "source": null,
      "source_name": "web",
      "name": "#37314505343276",
      "discount_codes": [
        {
          "code": "JULIA10",
          "amount": "2.30",
          "type": "percentage"
        }
      ],
      "total_discounts": "2.30",
      "total_line_items_price": "22.99",
      "total_price": "24.19",
      "total_tax": "1.58",
      "subtotal_price": "20.69",
      "total_duties": null,
      "abandoned_checkout_url": "https://www.nature-love.de/77580140844/checkouts/ac/Z2NwLWV1cm9wZS13ZXN0MTowMUhOV0dTSERFQzROWkQ3WkM1TU1GNFZQSw/recover?key=02114b307af3e1aa3c33e9a7648319f4&locale=de-DE",
      "shipping_lines": [
        {
          "code": "Standard Versandkosten",
          "price": "3.50",
          "source": "shopify",
          "title": "Standard Versandkosten",
          "presentment_title": "Standard Versandkosten",
          "validation_context": null,
          "phone": null,
          "markup": "0.00",
          "carrier_identifier": null,
          "carrier_service_id": null,
          "api_client_id": 580111,
          "delivery_option_group": {
            "token": "a8af3d50d77236e61bfb91c9372c9d99",
            "type": "one_time_purchase"
          },
          "delivery_expectation_range": null,
          "delivery_expectation_type": null,
          "tax_lines": [
            {
              "position": 0,
              "price": "0.23",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "0.23",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ],
      "tax_lines": [
        {
          "position": 1,
          "price": "1.58",
          "rate": 0.07,
          "title": "DE MwSt",
          "source": null,
          "compare_at": "1.58",
          "zone": null,
          "channel_liable": false,
          "identifier": null
        }
      ],
      "shipping_address": {
        "first_name": "Thomas",
        "address1": "Stromberger Str. 2a",
        "phone": "+4967247449",
        "city": "Daxweiler",
        "zip": "55442",
        "province": null,
        "country": "DE",
        "last_name": "Dreyse",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Thomas Dreyse",
        "country_code": "DE",
        "province_code": null
      },
      "billing_address": {
        "first_name": "Thomas",
        "address1": "Stromberger Str. 2a",
        "phone": "+4967247449",
        "city": "Daxweiler",
        "zip": "55442",
        "province": null,
        "country": "DE",
        "last_name": "Dreyse",
        "address2": null,
        "company": null,
        "latitude": null,
        "longitude": null,
        "name": "Thomas Dreyse",
        "country_code": "DE",
        "province_code": null
      },
      "line_items": [
        {
          "key": null,
          "destination_location_id": null,
          "fulfillment_service": "manual",
          "gift_card": false,
          "grams": 217,
          "origin_location_id": null,
          "presentment_title": "L-Lysin Kapseln",
          "presentment_variant_title": "365 Kapseln_für 6 Monate",
          "product_id": 8388745036076,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "nl_l-lysin_365",
          "taxable": true,
          "title": "L-Lysin Kapseln",
          "variant_id": 45725791322412,
          "variant_title": "365 Kapseln_für 6 Monate",
          "variant_price": "22.99",
          "vendor": "Nature Love",
          "unit_price_measurement": {
            "measured_type": "weight",
            "quantity_value": 217,
            "quantity_unit": "g",
            "reference_value": 1,
            "reference_unit": "kg"
          },
          "rank": null,
          "line_price": "22.99",
          "price": "22.99",
          "applied_discounts": [],
          "tax_lines": [
            {
              "position": 0,
              "price": "1.35",
              "rate": 0.07,
              "title": "DE MwSt",
              "source": null,
              "compare_at": "1.35",
              "zone": null,
              "channel_liable": false,
              "identifier": null
            }
          ]
        }
      ]
    }
  ]
}