#%RAML 1.0 Trait
responses:
  200:
    description: OK
    body:
      <<mimeType>>:
        type: <<successType>>
        example: <<successExample>>
  202:
    description: Accepted
    body:
      <<mimeType>>:
        type: <<successType>>
        example: <<successExample>>
  400:
    description: Bad Request
    body:
      <<mimeType>>:
        type: <<errorType>>
  404:
    description: Not Found
    body:
      <<mimeType>>:
        type: <<errorType>>
  405:
    description: Method Not Allowed
    body:
      <<mimeType>>:
        type: <<errorType>>
  406:
    description: Not Acceptable
    body:
      <<mimeType>>:
        type: <<errorType>>
  415:
    description: Unsupported Media Type
    body:
      <<mimeType>>:
        type: <<errorType>>
  422:
    description: Unprocessable Entity
    body:
      <<mimeType>>:
        type: <<errorType>>
  500:
    description: Internal Server Error
    body:
      <<mimeType>>:
        type: <<errorType>>
  501:
    description: Not Implemented
    body:
      <<mimeType>>:
        type: <<errorType>>