#%RAML 1.0
title: natsana-shopify-sapi
description: The Shopify System API processes the incoming requests to retrieve information about  Products, Variants and Abandoned Checkouts in order to synchronize to the Salesforce Sales Cloud backend system
version: v1 
protocols:
  - HTTPS

types:  
  Error: !include exchange_modules/75f6e0a4-0d0a-4491-8286-c723eb5c018c/error-data-type/1.0.0/error-data-type.raml
  PingResponse: !include dataTypes/PingResponse.raml
  ProductResponse: !include dataTypes/ProductsResponse.raml

traits:
  commonResponseOwner: !include exchange_modules/75f6e0a4-0d0a-4491-8286-c723eb5c018c/common-response-owner/1.0.2/common-response-owner.raml
 
  ClientId: !include traits/ClientIDRequiredTrait.raml
  ProductsQueryParams: !include traits/ProductsQueryParams.raml

/healthCheck:
  displayName: Health Check
  get:
    description: Get the current health status of this API
    is: 
    - commonResponseOwner: {mimeType: application/json, successType: PingResponse , successExample: !include examples/PingResponse.json, errorType: Error}

/products:
  displayName: Get Products
  description: This endpoint is used for retrieving Products 
  get:
    is: [ClientId, ProductsQueryParams, commonResponseOwner: {mimeType: application/json, successType: ProductResponse, successExample: !include examples/ProductsResponse.json, errorType: Error} ]

/checkouts:
  displayName: Get Checkouts
  description: This endpoint is used for retrieving Checkouts for a specific time  
  get:
    is: [ClientId, ProductsQueryParams, commonResponseOwner: {mimeType: application/json, successType: CheckoutsResponse, successExample: !include examples/CheckoutsResponse.json, errorType: Error} ]
    
    
    