#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: This security scheme validates requests to the API using BasicAuth Client Credentials.
  
describedBy:
  headers:
    Authorization: 
      description: Used to send a valid BasicAuth access token.
      type: string
  responses:
    401:
      description: Bad Credentials. Authentication failed.
      body:
        application/json:
          type: !include exchange_modules/75f6e0a4-0d0a-4491-8286-c723eb5c018c/error-data-type/1.0.0/error-data-type.raml
          examples:
            401: {
              httpStatus: 401,
              message: "Authentication failed.",
              httpReason: "Unauthorized"
            }
    403:
      description: The user authentication was successfull, but the user is not allowed to access the requested ressource.
      body:
        application/json:
          type: !include exchange_modules/75f6e0a4-0d0a-4491-8286-c723eb5c018c/error-data-type/1.0.0/error-data-type.raml
          examples:
            403: {
              httpStatus: 403,
              message: "The access to the requested ressource is forbidden.",
              httpReason: "Forbidden"
            }